### ISSUE TITLE
Solutions to odd-numbered problems

### ISSUE THREAD

**Issue by henryponti** [zenr/IMAUP-book-ed-2#1]
Hello,

I have adopted your book in my class, and I had a question regarding the solutions to the odd-numbered problems. On the introduction of the book (page xxvi), you mention that the solutions are available in this repository, but I was not able to locate the solutions for Chapters 1 and 2. Could you please let me know where to find them?

Thanks,
Henry

**Comment by zenr** [comment]
I apologize for not doing it earlier.  I will upload the solution to those 2 chapters soon.

**Comment by zenr** [comment]
@henryponti The solution to odd numbered problems for all chapters are available in the 'solutions' folder in the repo.
